# Generated by Django 5.2 on 2025-07-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_conos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocono',
            name='toppings',
            field=models.JSONField(blank=True, default=list, help_text='queso_extra, papas_al_hilo, salchicha_extra, huevo, salsa_picante, vegetales'),
        ),
    ]
